### ISSUE TITLE
Sanitize input

### ISSUE THREAD

**Issue by eirnym** [belchior/sql_query_builder#24]
all tables and columns are to be sanitized. 

Example following code:

```rust
    let select = sql::Select::new()
    .select("id, login")
    .from("us e \"rs")
    .where_clause("login = $1").as_string();

    println!("{select}");
```

which has invalid output:

```sql
SELECT id, login FROM us e "rs WHERE login = $1
```

**Comment by belchior** [comment]
Is recommended to use the driver layer to sanitize the SQL text before execute.
In [this issue](https://github.com/belchior/sql_query_builder/issues/1) has an example using tokio-postgres

**Comment by eirnym** [comment]
thank you for a suggestion, but this is not an option in case of tables. Thus, I don't see it as a duplicate. Additionally, drivers doesn't provide any way to this sanitisation, as there's impossible to insert parameters in `FROM` section.

FYI: table name may contain any kind of symbols and usually quoted with database-specific quotes separately.

**Comment by belchior** [comment]
In my first comment a think you try to report a SQL injection, thus I added the duplicate tag.

As said in the [main documentation](https://docs.rs/sql_query_builder/latest/sql_query_builder/#how-its-works) the library don't try to understand what you type inside the parameters, this make possible to write more idiomatic SQL queries but the down side is that it not detect typos or invalid SQL syntax. to minimize this annoying problem you can use the [debug method](https://docs.rs/sql_query_builder/latest/sql_query_builder/struct.Select.html#method.debug).

**Comment by eirnym** [comment]
It would be nice if sanitisation options will be provided by the library.
